= scheduleague

Schedule matches for sports leagues provided various parameters

* <<run,Run the application>>
* <<package,Run the packaged application>>
* <<container,Run the application in a container>>
* <<native,Run it native>>

== Prerequisites

. Install Java and Maven, for example with https://sdkman.io[Sdkman]:
+
----
$ sdk install java
----

[[run]]
== Run the application

. Git clone the scheduleague repo and navigate to this directory:
+
[source, shell]
----
$ git clone https://https://github.com/mikethecalamity/scheduleague.git
----

. Start the application with Gradle:
+
[source, shell]
----
$ cd java
$ ./gradlew quarkusDev
----

. Curl an input to the application.
+
[source, shell]
----
$ curl --header "Content-Type: application/json" -d @examples/request1.json http://localhost:8080
----

[[package]]
== Run the packaged application

When you're done iterating in `quarkus:dev` mode,
package the application to run as a conventional jar file.

. Build it with Gradle:
+
[source, shell]
----
$ ./gradlew clean build
----

. Run the Gradle output:
+
[source, shell]
----
$ java -jar ./build/quarkus-app/quarkus-run.jar
----
+
[NOTE]
====
To run it on port 8081 instead, add `-Dquarkus.http.port=8081`.
====

. Curl an input to the application.
+
[source, shell]
----
$ curl --header "Content-Type: application/json" -d @examples/request1.json http://localhost:8080
----

[[native]]
== Run it native

To increase startup performance for serverless deployments,
build the application as a native executable:

. https://quarkus.io/guides/building-native-image#configuring-graalvm[Install GraalVM and gu install the native-image tool]

. Compile it natively. This takes a few minutes:
+
[source, shell]
----
$ ./gradlew build -Dquarkus.native.enabled=true
----

. Run the native executable:
+
[source, shell]
----
$ ./target/*-runner
----

. Curl an input to the application.
+
[source, shell]
----
$ curl --header "Content-Type: application/json" -d @examples/request1.json http://localhost:8080
----

== More information

Visit https://timefold.ai[timefold.ai].
